<a href="https://colab.research.google.com/github/Mohan75489/Mohan75489/blob/main/Linear_Regression_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Predicting a dimension model
#2 dependent & 3 independent variables for a data point
'''DataPoint1: 73,62,44 gives 56,70
DataPoint1: 90,84,60 gives 82,104
DataPoint1: 71,155,58 gives 117,143
DataPoint1: 109,40,32 gives 20,42
DataPoint1: 69,99,74 gives 106,123'''

'DataPoint1: 73,62,44 gives 56,70\nDataPoint1: 90,84,60 gives 82,104\nDataPoint1: 71,155,58 gives 117,143\nDataPoint1: 109,40,32 gives 20,42\nDataPoint1: 69,99,74 gives 106,123'

In [7]:
#consider it as linear regression problem
#outputs (dependent variable) depends on each input(independent variables) with certain wait and a bias
'''Dim1=w11*dim1+w12*dim2+w13*dim3+b1
Dim2=w21*dim1+w22*dim2+w23*dim3+b2'''

'Dim1=w11*dim1+w12*dim2+w13*dim3\nDim2=w21*dim1+w22*dim2+w23*dim3'

In [8]:
#importing both numpy and PyTorch librarires
import torch
import numpy as np

Keeping one data point for checking model predictions.
Remaining 4 data points for training the model.

In [11]:
#taking inputs as numpy arrays and conversion to torch tensors
inputs = np.array([[73,62,44],[90,84,60],[71,155,58],[109,40,32]],dtype='float32')
targets = np.array([[56,70],[82,104],[117,143],[20,42]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  62.,  44.],
        [ 90.,  84.,  60.],
        [ 71., 155.,  58.],
        [109.,  40.,  32.]])
tensor([[ 56.,  70.],
        [ 82., 104.],
        [117., 143.],
        [ 20.,  42.]])


In [14]:
#creating random weights and biases
w = torch.randn(3,2, requires_grad=True) #beacause 3 rows and 2 columns
b = torch.randn(2, requires_grad=True) #because 2 rows and 1 column
print(w)
print(b)

tensor([[-0.5931,  0.0968],
        [-0.2538,  0.5006],
        [-1.5394, -1.3149]], requires_grad=True)
tensor([2.8887, 0.5801], requires_grad=True)


In [16]:
#creating a function to take inputs
def model(x):
    return x @ w +b

In [17]:
#predicting first time (obviously too much far from actual values)
predict = model(inputs)
print(predict)

tensor([[-123.8778,  -19.1739],
        [-164.1746,  -27.5541],
        [-167.8459,    8.7773],
        [-121.1746,  -10.9233]], grad_fn=<AddBackward0>)


In [18]:
#error or loss function (using mean sqaure error)
def mse(t1,t2):
      diff=t1-t2
      return torch.sum(diff*diff)/diff.numel()

In [19]:
#calculating loss using mse function created
loss = mse(predict,targets)
print(loss)

tensor(30012.5566, grad_fn=<DivBackward0>)


In [20]:
#loss is near to zero means model is predicting well (current model is too far from good)
#compute gradients, it's slope of loss function with respect to it's dependents (weights and biases).
loss.backward()
print(w)
print(w.grad)

tensor([[-0.5931,  0.0968],
        [-0.2538,  0.5006],
        [-1.5394, -1.3149]], requires_grad=True)
tensor([[-17724.7188,  -8412.0029],
        [-20407.2969,  -9875.1934],
        [-10930.9365,  -5323.8394]])
