<a href="https://colab.research.google.com/github/Mohan75489/Mohan75489/blob/main/Tensor_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#first tensor
t0 = torch.tensor(4.)

In [ ]:
t0

tensor(4.)

In [ ]:
#2D tensor
t2 = torch.tensor([[1.,2,3],[6,5,4]],requires_grad=True)
#3D tensor
t3 = torch.tensor([[[7,8,9],[10.,11,12]],[[14.,52,41],[15.,26,42.]]])
t3

tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[14., 52., 41.],
         [15., 26., 42.]]])

In [ ]:
t2

tensor([[1., 2., 3.],
        [6., 5., 4.]], requires_grad=True)

In [ ]:
#finding shape of tesor
t3.shape

torch.Size([2, 2, 3])

In [ ]:
#reshaping the tensor
#multiplicating value should be same while reshaping
t4=t3.reshape(6,2)
t4

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.],
        [14., 52.],
        [41., 15.],
        [26., 42.]])

In [ ]:
#numpy interoperability
import numpy as np

In [ ]:
#tensors in torch and array in numpy are interchangable
a = np.array([[2.,2],[7.,4]])
a

array([[2., 2.],
       [7., 4.]])

In [ ]:
#numpy array to torch tensor coversion
b = torch.from_numpy(a)
b

tensor([[2., 2.],
        [7., 4.]], dtype=torch.float64)

In [ ]:
#data types of torch and numpy are appears to be same but the aren't
a.dtype,b.dtype

(dtype('float64'), torch.float64)

In [ ]:
#conversion of torch tensor to numpy array
c = b.numpy()
c

array([[2., 2.],
       [7., 4.]])

Reading and preporcessing is done through numpy library of Python.
But, torch is better for ML/DL problems because of it's ability to calculate Autograd adn operability on GPUs.

In [ ]:
#arthemetic operations on tensor
t1 = t2+t3
t1

tensor([[[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]]])

In [ ]:
t2.shape

torch.Size([2, 3])

In [ ]:
t4.shape

torch.Size([6, 2])

In [ ]:
#for concatenation shape should of same shape
t5 = torch.cat(t2,t4)
t5

TypeError: ignored

In [ ]:
t6 = torch.tensor([[5,6,7.],[91,23.,4]])
t6.shape

torch.Size([2, 3])

In [ ]:
t5 = torch.cat((t2,t6))
t5

tensor([[ 1.,  2.,  3.],
        [ 6.,  5.,  4.],
        [ 5.,  6.,  7.],
        [91., 23.,  4.]])

In [ ]:
#repitative tensor with certain shape
t7 = torch.full((2,2),5.,requires_grad=True)
t7

tensor([[5., 5.],
        [5., 5.]], requires_grad=True)

In [ ]:
t8 = torch.tensor(5., requires_grad=True)
t9 = torch.tensor(4.)
t10 = torch.tensor(2., requires_grad=True)

In [ ]:
t11 = t8 * t9 + t10

In [ ]:
# gradients can only be possible for SCALAR outputs
t11.backward()

In [ ]:
print(t8.grad)
print(t9.grad)
print(t10.grad)

tensor(4.)
None
tensor(1.)


In [ ]:
#other PyTorch functions
torch.is_tensor(t1)

True

In [ ]:
torch.is_storage(t2)

False

In [ ]:
#length of the tensor (multiplication of shape values)
torch.numel(t7)

4

In [ ]:
torch.set_printoptions(t0)

In [ ]:
t0

tensor(4.)