<a href="https://colab.research.google.com/github/Mohan75489/DeepLearning_PyTorch/blob/main/Tensor_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#first tensor
t0 = torch.tensor(4.)

In [3]:
t0

tensor(4.)

In [4]:
#2D tensor
t2 = torch.tensor([[1.,2,3],[6,5,4]],requires_grad=True)
#3D tensor
t3 = torch.tensor([[[7,8,9],[10.,11,12]],[[14.,52,41],[15.,26,42.]]])
t3

tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[14., 52., 41.],
         [15., 26., 42.]]])

In [5]:
t2

tensor([[1., 2., 3.],
        [6., 5., 4.]], requires_grad=True)

In [6]:
#finding shape of tesor
t3.shape

torch.Size([2, 2, 3])

In [7]:
#reshaping the tensor
#multiplicating value should be same while reshaping
t4=t3.reshape(6,2)
t4

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.],
        [14., 52.],
        [41., 15.],
        [26., 42.]])

In [8]:
#numpy interoperability
import numpy as np

In [9]:
#tensors in torch and array in numpy are interchangable
a = np.array([[2.,2],[7.,4]])
a

array([[2., 2.],
       [7., 4.]])

In [10]:
#numpy array to torch tensor coversion
b = torch.from_numpy(a)
b

tensor([[2., 2.],
        [7., 4.]], dtype=torch.float64)

In [11]:
#data types of torch and numpy are appears to be same but the aren't
a.dtype,b.dtype

(dtype('float64'), torch.float64)

In [12]:
#conversion of torch tensor to numpy array
c = b.numpy()
c

array([[2., 2.],
       [7., 4.]])

Reading and preporcessing is done through numpy library of Python.
But, torch is better for ML/DL problems because of it's ability to calculate Autograd adn operability on GPUs.

In [13]:
#arthemetic operations on tensor
t1 = t2+t3
t1

tensor([[[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]]], grad_fn=<AddBackward0>)

In [14]:
t2.shape

torch.Size([2, 3])

In [15]:
t4.shape

torch.Size([6, 2])

In [21]:
#for concatenation shape should of same shape
t5 = torch.cat([t2,t4],dim=6)
t5

IndexError: ignored

In [22]:
t6 = torch.tensor([[5,6,7.],[91,23.,4]])
t6.shape

torch.Size([2, 3])

In [23]:
t5 = torch.cat((t2,t6))
t5

tensor([[ 1.,  2.,  3.],
        [ 6.,  5.,  4.],
        [ 5.,  6.,  7.],
        [91., 23.,  4.]], grad_fn=<CatBackward0>)

In [24]:
#repitative tensor with certain shape
t7 = torch.full((2,2),5.,requires_grad=True)
t7

tensor([[5., 5.],
        [5., 5.]], requires_grad=True)

In [25]:
t8 = torch.tensor(5., requires_grad=True)
t9 = torch.tensor(4.)
t10 = torch.tensor(2., requires_grad=True)

In [26]:
t11 = t8 * t9 + t10

In [27]:
# gradients can only be possible for SCALAR outputs
t11.backward()

In [28]:
print(t8.grad)
print(t9.grad)
print(t10.grad)

tensor(4.)
None
tensor(1.)


In [29]:
#other PyTorch functions
torch.is_tensor(t1)

True

In [30]:
torch.is_storage(t2)

False

In [31]:
#length of the tensor (multiplication of shape values)
torch.numel(t7)

4

In [32]:
torch.set_printoptions(t0)

In [33]:
t0

tensor(4.)

In [37]:
t1

tensor([[[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]]], grad_fn=<AddBackward0>)

In [78]:
#dim range is from -3 to 2
t8 = torch.cat([t1,t1,t1],dim=-3)
t8

tensor([[[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]],

        [[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]],

        [[ 8., 10., 12.],
         [16., 16., 16.]],

        [[15., 54., 44.],
         [21., 31., 46.]]], grad_fn=<CatBackward0>)

In [67]:
t1.sum()

tensor(289., grad_fn=<SumBackward0>)

In [69]:
#taking items from tensors, only for scalar tensors
t1.sum().item()

289.0

In [80]:
#in place operators "_"
t8.copy_(t0)
t8

tensor([[[4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.]]], grad_fn=<CopyBackwards>)

To run on GPU we need to call CUDA

In [100]:
t12 = torch.arange(1,20,1)
t12

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [130]:
torch.set_num_threads(2)

In [131]:
torch.get_num_threads()

2